# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'

# Enhanced cdl function using smart navigation (yours + his)
cdl() {
    zd "$@"
    eza -lh --group-directories-first --icons=auto
}

alias gst='git status'
alias gd='git diff -U0'

gam() {
  for file in "${@:1:$#-1}"; do
    git add $file
  done
  git commit -m "${!#}"
}

restart() {
    source "$HOME/.local/share/omarchy/default/bashrc" 2>/dev/null || source "$HOME/.bashrc"
}

alias now='date +%F\ %T'
alias weather='curl wttr.in/Dallas?0'
alias rsync='rsync -azH --info=progress2'
alias code='uwsm app -- /usr/share/positron/bin/positron --disable-gpu'
