---
title: "NHANES Aging Study"
date: last-modified
---


```{r}
#| label: setup
source('R/_libraries.R')
source('R/custom_table_functions.R')
source('R/custom_functions.R')

# imported <- read_csv('data/comprehensive_nhanes_dataset_2009_2018.csv')

# Save the data object for faster & less-verbose loading
# save(imported, file = 'data/imported_nhanes_2009_2018.rda')
load('data/imported_nhanes_2009_2018.rda')
```

```{r}
#| label: custom functions
#| echo: false

# This URL will direct you to the list of interviewer manuals & questionnaire instruments
# https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/questionnaires.aspx?Cycle=2021-2023

# NOTE: the PDF links on the page provide a questionnaire, but not all variables may be 
# listed compared to when using `nhanes("DIQ_L") |> names()`.
# The custom `get_url()` function is needed to get the link to the full set of variables
# from the codebook!

#----------------------------------------------------------------------------------------
#' Custom function to retrieve the codebook URL
#' @param table Character. The table where variable information is needed.
#' @returns Full URL to CDC data documentation, codebook, & frequencies.
get_url <- function(table) {
  paste0(
    "https://wwwn.cdc.gov",
    nhanesManifest() |> 
      filter(Table == table) |> 
      pull(DocURL)
  ) |> 
  message()
}

#----------------------------------------------------------------------------------------
#' Custom wrappe function to nhanesA::nhanesSearch for concise output
#' @param var Character. Term or phrase to search
#' @returns Smaller output dataset
var_search <- function(var) {
  nhanesA::nhanesSearch(var) |> 
    select(1:3, Begin.Year)
}
```

```{r}
#| label: variable selection
reduced <- imported |> 
  select(
    year = RIDYEAR...2,
    seqn = SAMPLEID,  # ID number
    WTMEC2YR,
    WTINT2YR,
    SDMVPSU,
    SDMVSTRA,
    
    # Demographics
    RIAGENDR,  # Sex
    RIDAGEYR,  # Age
    RIDRETH1,  # Race/Hispanic origin
    RIDRETH3,  # Race/Hispanic origin w/ NH Asian
    DMDEDUC2,  # Education level - Adults 20+
    INDHHIN2,  # Annual household income

    contains('DERIVED'),
    contains('KDM'),

    # Substance usage variables
    contains('DUQ'),
    
  ) |> 
  # Convert variable names from uppercase to lowercase
  janitor::clean_names() |> 
  rename(
    derived_nonhdl_cholesterol = nonhdl,
    derived_pulse_pressure_alt = pp,
    derived_albumin_creatinine_ratio = acr,
    derived_alt_proxy = alt,
    
    derived_mean_blood_pressure = meanbp,
    derived_pulse_pressure = pulse,
    derived_fev1_1000 = fev1_1000,
    derived_albumin_g_l = albumin_gL,
    derived_ln_alp = lnalp,
    derived_ln_bun = lnbun,
    derived_creat_umol = creat_umol,
    derived_ln_creat = lncreat,
    derived_ln_creat_umol = lncreat_umol,
    derived_glucose_mmol = glucose_mmol,
    derived_ln_uap = lnuap,
    derived_crp_category = crp_cat,
    derived_ln_crp = lncrp,
    derived_ln_hba1c = lnhba1c,
    derived_grip_scaled = grip_scaled,
    derived_ln_walk = lnwalk

  )
```


```{r}
#| label: variable cleaning
the_data <- reduced |> 
  mutate(
    year = as_factor(as.integer(year)),
    riagendr = case_when(
      riagendr == 1 ~ 'Male',
      riagendr == 2 ~ 'Female',
      .default = as.character(riagendr)
    ),

    # ---------------------------------------------------------
    # Ref: https://wwwn.cdc.gov/nchs/nhanes/tutorials/Weighting.aspx
    # Then expand this section: When and How to Construct Weights When Combining Survey Cycles
    survey_weights_mec = wtmec2yr / 5,
    survey_weight_int = wtint2yr / 5,
    # ---------------------------------------------------------

    ridageyr = as.integer(ridageyr),
    ridreth3 = case_when(
      ridreth3 == 1 ~ 'Mexican American',
      ridreth3 == 2 ~ 'Other Hispanic',
      ridreth3 == 3 ~ 'Non-Hispanic White',
      ridreth3 == 4 ~ 'Non-Hispanic Black',
      ridreth3 == 6 ~ 'Non-Hispanic Asian',
      ridreth3 == 7 ~ 'Other Race, Including Multi-Racial',
      .default = as.character(ridreth3)
    ),
    dmdeduc2 = factor(
      case_when(
        dmdeduc2 == 1 ~ 'Less than 9th grade',
        dmdeduc2 == 2 ~ '9th to 11th grade (including 12th grade with no diploma)',
        dmdeduc2 == 3 ~ 'High school graduate (including GED)',
        dmdeduc2 == 4 ~ 'Some college or associate\'s degree',
        dmdeduc2 == 5 ~ 'College graduate or above',
        dmdeduc2 == 7 ~ 'Refused',
        dmdeduc2 == 9 ~ 'Don\'t know',
        .default = as.character(dmdeduc2)
      ),
      levels = c(
        'Less than 9th grade',
        '9th to 11th grade (including 12th grade with no diploma)',
        'High school graduate (including GED)',
        'Some college or associate\'s degree',
        'College graduate or above',
        'Refused', 'Don\'t know'
      ),
      ordered = TRUE),
    indhhin2 = factor(
      case_when(
        indhhin2 == 1 ~ '$0 to $4,999',
        indhhin2 == 2 ~ '$5,000 to $9,999',
        indhhin2 == 3 ~ '$10,000 to $14,999',
        indhhin2 == 4 ~ '$15,000 to $19,999',
        indhhin2 == 5 ~ '$20,000 to $24,999',
        indhhin2 == 6 ~ '$25,000 to $34,999',
        indhhin2 == 7 ~ '$35,000 to $44,999',
        indhhin2 == 8 ~ '$45,000 to $54,999',
        indhhin2 == 9 ~ '$55,000 to $64,999',
        indhhin2 == 10 ~ '$65,000 to $74,999',
        indhhin2 == 12 ~ 'Over $20,000',
        indhhin2 == 13 ~ 'Under $20,000',
        indhhin2 == 14 ~ '$75,000 to $99,999',
        indhhin2 == 15 ~ '$100,000 and over',
        indhhin2 == 77 ~ 'Refused',
        .default = as.character(indhhin2)
      ),
      levels = c(
        '$0 to $4,999',
        '$5,000 to $9,999',
        '$10,000 to $14,999',
        '$15,000 to $19,999',
        '$20,000 to $24,999',
        '$25,000 to $34,999',
        '$35,000 to $44,999',
        '$45,000 to $54,999',
        '$55,000 to $64,999',
        '$65,000 to $74,999',
        'Over $20,000',
        'Under $20,000',
        '$75,000 to $99,999',
        '$100,000 and over',
        'Refused'
      ),
      ordered = TRUE
    ),

    # Substance use variables ----

    # Time since last used marijuana regularly
    duq215 = case_when(
      is.na(duq215u) ~ NA_integer_,
      is.na(duq215q) ~ NA_integer_,
      duq215q > 700 ~ NA_integer_,
      # Convert all to years
      duq215u == 1 ~ duq215q / 365,
      duq215u == 2 ~ duq215q / 52,
      duq215u == 3 ~ duq215q / 12,
      duq215u == 4 ~ duq215q,
      .default = 999
    ),

    # Time since last used marijuana / hashish
    duq220 = case_when(
      is.na(duq220u) ~ NA_integer_,
      is.na(duq220q) ~ NA_integer_,
      duq220q > 700 ~ NA_integer_,
      # Convert all to years
      duq220u == 1 ~ duq220q / 365,
      duq220u == 2 ~ duq220q / 52,
      duq220u == 3 ~ duq220q / 12,
      duq220u == 4 ~ duq220q,
      .default = 999
    ),

    # Time since last used cocaine
    duq270 = case_when(
      is.na(duq270u) ~ NA_integer_,
      is.na(duq270q) ~ NA_integer_,
      duq270q > 700 ~ NA_integer_,
      # Convert all to years
      duq270u == 1 ~ duq270q / 365,
      duq270u == 2 ~ duq270q / 52,
      duq270u == 3 ~ duq270q / 12,
      duq270u == 4 ~ duq270q,
      .default = 999
    ),

    # Time since last used heroin
    duq310 = case_when(
      is.na(duq310u) ~ NA_integer_,
      is.na(duq310q) ~ NA_integer_,
      duq310q > 700 ~ NA_integer_,
      # Convert all to years
      duq310u == 1 ~ duq310q / 365,
      duq310u == 2 ~ duq310q / 52,
      duq310u == 3 ~ duq310q / 12,
      duq310u == 4 ~ duq310q,
      .default = 999
    ),

    # Time since last used methamphetamine
    duq350 = case_when(
      is.na(duq350u) ~ NA_integer_,
      is.na(duq350q) ~ NA_integer_,
      duq350q > 700 ~ NA_integer_,
      # Convert all to years
      duq350u == 1 ~ duq350q / 365,
      duq350u == 2 ~ duq350q / 52,
      duq350u == 3 ~ duq350q / 12,
      duq350u == 4 ~ duq350q,
      .default = 999
    ),

    # Time since last used injectable drug
    duq400 = case_when(
      is.na(duq400u) ~ NA_integer_,
      is.na(duq400q) ~ NA_integer_,
      duq400q > 700 ~ NA_integer_,
      # Convert all to years
      duq400u == 1 ~ duq400q / 365,
      duq400u == 2 ~ duq400q / 52,
      duq400u == 3 ~ duq400q / 12,
      duq400u == 4 ~ duq400q,
      .default = 999
    ),

    # Cannabis variables ----

    # Ever used marijuana or hashish
    duq200 = case_when(
      duq200 == 1 ~ 'Yes',
      duq200 == 2 ~ 'No',
      duq200 == 7 ~ 'Refused',
      duq200 == 9 ~ 'Don\'t know',
      .default = as.character(duq200)
    ),

    ever_use_marijuana = case_when(
      duq200 == 'Yes' ~ 'Yes',
      duq200 == 'No' ~ 'No',
      .default = 'Unknown'
    ),

    # During the past 30 days, on how many days did you use marijuana or hashish?
    # duq230

    # Use classification
    # 1.  Never users 
    # 2.	Former users (at least once in lifetime but not in past 30 days)
    # 3.	Current light user (at least once in the last 30 days but not on more than four different days)
    # 4.	Current heavy user (at least five different days in the last 30 days).
    use_category = factor(
      case_when(
        duq200 == 'Yes' & duq230 >= 5 ~ 'Current heavy user',
        duq200 == 'Yes' & between(duq230, 1, 4) ~ 'Current light user',
        duq200 == 'Yes' & duq230 < 1 ~ 'Former user',
        duq200 == 'No' ~ 'Never used',

        duq200 == 'Yes' & is.na(duq230) ~ 'Former user',
        # These participants were either refused, don't know, or missing by system
        .default = 'Missing'  
      ),
      levels = c(
        'Current heavy user',
        'Current light user',
        'Former user',
        'Never used',
        'Missing'
      ),
      ordered = TRUE
    )
  ) 

save(the_data, file = 'data/study_data.rda')
```

