---
title: ""
date: last-modified
---


```{r}
#| label: setup
source('R/_libraries.R')
source('R/data_dictionary.R')
load('data/the_data.rda')

reduced <- the_data |> 
  filter(between(year, 1999, 2010))
```

```{r}
#| label: set-up definitions
# Definition 1: Diagnosis of diabetes before age 30 years, taking insulin now, started 
# taking insulin within one year of diagnosis.
defined <- reduced |> 
  mutate(
    # Definition 1: Diagnosis of diabetes before age 30 years, taking insulin now, started 
    # taking insulin within one year of diagnosis.
    definition_one = case_when(
      (
        # Diagnosis of diabetes before age 30 (var: did040)
        # did040 < 30 &
        age_told_diabetes < 30 &
          # taking insulin now (var: diq050)
          diq050 == 'Yes' &
          # started taking insulin within one year of diagnosis 
          # (var: did060 -- how long taking insulin)
          insulin_within_1yr == TRUE
      ) ~ 'Type 1',
      .default = 'not Type 1'
    ),

    # Definition 2: Diagnosis of diabetes before age 40 years, taking insulin now, 
    # started taking insulin within one year of diagnosis.
    definition_two = case_when(
      (
        # Diagnosis of diabetes before age 40 (var: did040)
        # did040 < 40 &
        age_told_diabetes < 40 &
          # taking insulin now (var: diq050)
          diq050 == 'Yes' &
          # started taking insulin within one year of diagnosis 
          # (var: did060 -- how long taking insulin)
          insulin_within_1yr == TRUE
      ) ~ 'Type 1',
      .default = 'not Type 1'
    ),
  )
```


```{r}
#| label: view results
# Updated on 10.9.2025 -- after reprocessing variables & modifying variable names. See
# the newly-revised data_pull.qmd file (specifically section on DIQ_* diabetes data).
defined |> 
  tabyl(definition_one) |> 
  adorn_pct_formatting(digits = 2)
#  definition_one     n percent
#          Type 1   189   0.21%
#      not Type 1 89543  99.79%
defined |> 
  tabyl(definition_two) |> 
  adorn_pct_formatting(digits = 2)
#  definition_two     n percent
#          Type 1   270   0.30%
#      not Type 1 89462  99.70%
```

The original study identified "59,130 NHANES participants, 123 individuals met the 
definition 1 criteria and 160 the definition 2 criteria." However, our study analyzed 
89,732 participants where 189 met the definition 1 criteria and 270 met the definition 2 
criteria. This represents increases of 53.7% and 28.8% for each definition respectively.

## Create a survey design object
